name: themefinder tests

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        run: |
          python -m pip install --upgrade poetry
          poetry install

      - name: Run tests with Pytest
        run: |
          poetry run coverage run -m pytest -v -s

      - name: Generate coverage report
        run: |
          poetry run coverage report -m --fail-under=95

